### ISSUE TITLE
player & egg tag

### ISSUE THREAD

**Issue by Alanine42** [ucsd-cse125-sp24/group5#40]
draw player tag
- player 1,2,3,4
- team color^

draw egg tag
- shining tag above the egg
- this one should be above any world element or screen element ---- you can always see where the egg is ---- a billboard you can see regardless of obstruction

**Comment by luoluobuli** [comment]
I feel the egg tag kinda blocks the player's view
![Screenshot 2024-06-02 025050](https://github.com/ucsd-cse125-sp24/group5/assets/121198882/c2e84441-5aa8-466b-b425-db4f54d8b1e4)

**Comment by Alanine42** [comment]
it'll be wayy smaller when you're carrying it

**Comment by Alanine42** [comment]
(sorry we should've test that yesterday)

**Comment by Alanine42** [comment]
actually i'll just remove the egg tag all over when the player carries it. 

(moving it to bottom left UI, with the player tag)
