### ISSUE TITLE
UI in game

### ISSUE THREAD

**Issue by luoluobuli** [ucsd-cse125-sp24/group5#67]
- Remove the text on the icon? I think showing the seasons with text is kind of unecessary because we've made it very clear which season it is with ui and the map itself. A suggestion from art person: less is more.
- Color the scoreboard, make team red's score red and team blue's blue so there's no confusion.
- Maybe make the player's name tag smaller? I still feel that they're unecessarily too big. Half the size should be good.

**Comment by Alanine42** [comment]
ok, on it

**Comment by realmatthewpeng** [comment]
#74
